#────────────────────────────────────────────────────────────────
# Main website config
# file: _quarto.yml
# ───────────────────────────────────────────────────────────────

project:
  type: website
  output-dir: _site
  preview:
    port: 4444
    browser: true

execute:
  freeze: auto
  #cache: true

website:
  title: "[energycode]"
  site-url: "https://www.energycode.org"
  repo-url: "https://github.com/EnriquePH/energycode.org"
  repo-branch: main
  repo-actions: [edit, source, issue]
  description: >
    My personal blog on Data Science, Mathematics, Engineering and Programming
  google-analytics: "G-6P3MCX2KHD"
  favicon: /img/logo/favicon.ico

# Main menu and tools
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        href: https://github.com/EnriquePH
        aria-label: "GitHub"
      - icon: stack-overflow
        href: https://stackoverflow.com/users/4678112/enrique-p%c3%a9rez-herrero
      - icon: twitter-x
        href: https://twitter.com/energycodeorg
      - icon: envelope-at
        href: mailto:energycode.org@gmail.com
        aria-label: "email"
    left:
      - index.qmd
      - projects.qmd
      - about.qmd

format:
  html:
    theme:
      light: lux
      dark:  darkly
    css: styles.css

    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: show
    code-copy: hover
    code-overflow: wrap
    highlight-style: github

    # Mejora la accesibilidad y apariencia
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true

# Default editor
editor: source
email-obfuscation: javascript
